name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify

      - name: SonarCloud Analysis
        working-directory: simple-api
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=hissein02_tp-devops-correction-docker -Dsonar.organization=hissein02 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest

      - name: Build image and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./devops-front-main
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-frontend:latest

  deploy-on-server:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout ansible repository
        uses: actions/checkout@v4
        with:
          repository: hissein02/DevOPs_MLOps
          path: DevOPs_MLOps
          token: ${{ secrets.ANSIBLE_REPO_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Deploy with Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          cd DevOPs_MLOps/tp3/ansible
          echo "${{ secrets.DEPLOY_KEY }}" > ./id_rsa
          chmod 600 ./id_rsa
          
          echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt
          ansible-playbook -i inventories/setup.yml playbook.yml --vault-password-file vault_pass.txt --private-key ./id_rsa
          rm vault_pass.txt id_rsa
